### ISSUE TITLE
Spell Save DCs dont use prof dice

### ISSUE THREAD

**Issue by adacosta92** [NekroDarkmoon/optional-rules-dnd5e#13]
Currently, only attacks use the proficiency dice in place of the bonus, but Spell Save DCs should as well.

**Comment by NekroDarkmoon** [comment]
In the implementation of the proficiency die I went with the following interpretation:

`Instead of adding a proficiency bonus to an ability check, an attack roll, or saving throw, the character's player rolls a die.`

And based on that the spell save DC would be a static number based on the table in the dmg. It would be a lot harder to mess with actor sheets to calculate DC while accounting for proficiency die and could possibly lead to data corruption if the module fails to load or is disabled.

**Comment by adacosta92** [comment]
Fair enough. Thanks!

Best,

Ajay

________________________________
